### ISSUE TITLE
Building on macOS

### ISSUE THREAD

**Issue by shradej1** [cmr/netlib-src#7]
Not sure if this is an issue with netlib-src or lapack (or me), but I'm unable to use this library on macOS.  I have gcc / gfortran installed via homebrew, but the linker is unable to locate the libgfortran libraries.  Running "cargo test" results in

error: linking with `cc` failed: exit code: 1
  <snip>
  = note: ld: library not found for -lgfortran
          clang: error: linker command failed with exit code 1 (use -v to see invocation)

Is this a supported platform?

**Comment by IvanUkhov** [comment]
I have the same problem. I think it arises when Homebrew is set up to install software in a custom directory without requiring the root privileges. In this case, the linker fails to find the needed `libgfortran.dylib`. The workaround that I have been using is as follows:

```shell
ln -s "`brew --prefix`/Cellar/gcc/6.3.0_1/lib/gcc/6/libgfortran.dylib" ~/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib/
```

Adjust to reflect your versions of GCC and of the Rust toolchain.

If somebody knows a better way to make it work, please do let me know. Thanks!

**Comment by IvanUkhov** [comment]
Another solution can be seen in [this](https://github.com/stainless-steel/stainless-steel.github.io/blob/master/travis/fortran.sh) script, which is how it works on Travis CI’s infrastructure:

```bash
#!/bin/bash

set -v

if [ "${TRAVIS_OS_NAME}" == "osx" ]; then
  brew uninstall gcc49
  while true; do
    curl -L http://prdownloads.sourceforge.net/hpc/gcc-6.2-bin.tar.gz -o archive.tar.gz && break
  done
  mkdir root && tar -xzf archive.tar.gz -C root && sudo cp -R root/* /
fi

gfortran --version
```

Here I’m just installing GCC right into the root of the filesystem.

**Comment by shradej1** [comment]
That I think got me part of the way there...  now `cargo test` fails in `rustdoc --test` because

`dyld: Symbol not found: _appleblas_i16gemm
  Referenced from: /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBNNS.dylib
  Expected in: /Users/.../rblas/target/debug/build/netlib-src-da4bf3f3106af0b5/out/lib/libBLAS.dylib
 in /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBNNS.dylib
`

I'm guessing the libBLAS.dylib being built by rust is getting picked up by the accelerate framework rather than its own libBLAS.dylib.

    $ otool -L /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBNNS.dylib
    /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBNNS.dylib:
    /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBNNS.dylib (compatibility version 1.0.0, current version 1.0.0)
    /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib (compatibility version 1.0.0, current version 1.0.0)
    /usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1238.0.0)

I should note that my lib.rs file contains a single line - `extern crate netlib_src`

Looks like this might be related to [https://github.com/rust-lang/rust/issues/25289](https://github.com/rust-lang/rust/issues/25289)?

**Comment by IvanUkhov** [comment]
This crate doesn’t have any bindings. What kind of code are you testing?

**Comment by IvanUkhov** [comment]
The link you gave seems to be broken.

**Comment by shradej1** [comment]
Sorry, I updated the link.  That's just it though - there's nothing to test.  I list netlib-src as my only dependency in Cargo.toml, and lib.rs is a single line - "extern crate netlib_src;"  I run `cargo test` and get the above error.

**Comment by IvanUkhov** [comment]
You’re right. I also get the exact same error with Netlib’s implementation (`netlib-src`). OpenBLAS’s one works just fine (`openblas-src`). It used to work. Something has changed recently.

**Comment by IvanUkhov** [comment]
The interesting thing is that it works on Travis CI. Have a look [here](https://travis-ci.org/stainless-steel/blas-sys/builds/195091463). All BLAS providers with respect to all Rust channels are green. Maybe it’s something related to the version of the OS used. I have Sierra, and I guess you too. Travis CI, on the other hand, has El Capitan.

**Comment by shradej1** [comment]
I am running Sierra, although I tried on 10.11.6 (El Capitan) as well, and got a similar error.  

    dyld: Symbol not found: _cblas_dgemm
    Referenced from: /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libvDSP.dylib
    Expected in: /Users/shradej1/IdeaProjects/rblas/target/debug/build/netlib-src-da4bf3f3106af0b5/out/lib/libBLAS.dylib
    in /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libvDSP.dylib

Either way, I think your cargo ticket captures the problem.  Definitely something different going on when cargo tries to run doc tests vs other tests.  I'll keep an eye on that ticket.  Thanks!

**Comment by IvanUkhov** [comment]
@shradej1, can you please try what’s on master? That error with `_appleblas_i16gemm` should be gone. Thanks!

**Comment by shradej1** [comment]
That did it.  Thanks!
