### ISSUE TITLE
Is libtmglib necessary?

### ISSUE THREAD

**Issue by Rufflewind** [cmr/netlib-src#9]
In my particular use case, I'm (ab)using `netlib-src` to link to a system BLAS/LAPACK-like library, which is unlikely to have to `libtmglib.so`.  Given that it's mostly used for testing, perhaps there should be a way to at least disable linkage to it.

**Comment by IvanUkhov** [comment]
Thank you for the issue. I think it’s reasonable to provide such a possibility, since there are features for CBLAS and LAPACKE. Please feel free to open a pull request.

**Comment by IvanUkhov** [comment]
I suppose this new feature should be called `tmg`, and it should be enabled by default.
